apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: mercator-api
    version: 1.0.2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mercator-api
  template:
    metadata:
      labels:
        app: mercator-api
    spec:
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code-claim
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: site.conf
      containers:
      - name: nginx
        image: nginx:1.15.9
        ports:
        - containerPort: 80
        volumeMounts:
          - name: code
            mountPath: /code
          - name: config
            mountPath: /etc/nginx/conf.d
      - name: php
        image: php:7.3-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
          - name: code
            mountPath: /code
